// Code generated by internal/descriptor/gen from verizon_family.json; DO NOT EDIT.

package main

// generatedAreas is the subcommand tree docs/CLI-DESIGN.md describes: one area per
// command group, one verb per cli block, every flag typed. It is embedded in CLI.
type generatedAreas struct {
	PauseInternet PauseInternetArea `cmd:"" name:"pause-internet" help:"Pause or resume a child's internet right now, and read the current pause state."`
}

// PauseInternetArea groups the pause-internet verbs (core verbs first).
type PauseInternetArea struct {
	Pause  PauseInternetPauseCmd  `cmd:"" name:"pause" help:"Pause the child's internet now, for a fixed time or until you resume it.\nPrerequisite: The child's phone must be PAIRED (the PAIRING column of 'safe_cli members' reads PAIRED or UNPAIRED).\nAn UNPAIRED target is refused; pass --allow-unpaired to send anyway."`
	Resume PauseInternetResumeCmd `cmd:"" name:"resume" help:"Resume the child's internet, lifting a pause.\nPrerequisite: The child's phone must be PAIRED (the PAIRING column of 'safe_cli members' reads PAIRED or UNPAIRED).\nAn UNPAIRED target is refused; pass --allow-unpaired to send anyway."`
	Status PauseInternetStatusCmd `cmd:"" name:"status" help:"Show whether the child's internet is paused, how long is left, and the valid pause timings."`
}

// PauseInternetPauseCmd: pause-internet pause <- pause_internet.pauseInternet
type PauseInternetPauseCmd struct {
	Child         *string `name:"child" help:"The child, by the SERVICE-ID that 'safe_cli members' prints. Required."`
	For           *string `name:"for" help:"How long to pause: 30m|1h|2h|4h|until-morning (default: 30m). until-morning lifts the pause at the child's next morning. Ignored with --indefinite."`
	Indefinite    *bool   `name:"indefinite" help:"Pause until you run 'pause-internet resume' (sends untilIUnpause=true and omits pauseSchedule). (default: false)"`
	CallOnly      *bool   `name:"call-only" help:"Leave phone calls working while data is paused (default: false)."`
	Timezone      *string `name:"timezone" help:"Short zone code (EST, PST) the pause timing is computed in (default: this machine's local zone)."`
	DryRun        bool    `name:"dry-run" help:"Print the exact request, with the resolved ids, without sending it."`
	AllowUnpaired bool    `name:"allow-unpaired" help:"Send even though the child's device is not PAIRED."`
}

func (c *PauseInternetPauseCmd) Run(rc *runContext) error {
	given := map[string]any{}
	if c.For != nil {
		given["for"] = *c.For
	}
	if c.Indefinite != nil {
		given["indefinite"] = *c.Indefinite
	}
	if c.CallOnly != nil {
		given["call-only"] = *c.CallOnly
	}
	if c.Timezone != nil {
		given["timezone"] = *c.Timezone
	}
	return runVerb(rc, "pause_internet", "pauseInternet", "pause-internet", "pause", given, deref(c.Child), c.DryRun, false, c.AllowUnpaired)
}

// PauseInternetResumeCmd: pause-internet resume <- pause_internet.unPauseInternet
type PauseInternetResumeCmd struct {
	Child         *string `name:"child" help:"The child, by the SERVICE-ID that 'safe_cli members' prints. Required."`
	DryRun        bool    `name:"dry-run" help:"Print the exact request, with the resolved ids, without sending it."`
	AllowUnpaired bool    `name:"allow-unpaired" help:"Send even though the child's device is not PAIRED."`
}

func (c *PauseInternetResumeCmd) Run(rc *runContext) error {
	given := map[string]any{}
	return runVerb(rc, "pause_internet", "unPauseInternet", "pause-internet", "resume", given, deref(c.Child), c.DryRun, false, c.AllowUnpaired)
}

// PauseInternetStatusCmd: pause-internet status <- pause_internet.getDevices
type PauseInternetStatusCmd struct {
	Child  *string `name:"child" help:"The child, by the SERVICE-ID that 'safe_cli members' prints. Required."`
	DryRun bool    `name:"dry-run" help:"Print the exact request, with the resolved ids, without sending it."`
}

func (c *PauseInternetStatusCmd) Run(rc *runContext) error {
	given := map[string]any{}
	return runVerb(rc, "pause_internet", "getDevices", "pause-internet", "status", given, deref(c.Child), c.DryRun, false, false)
}
